#!/bin/bash

usage()
{
    echo "Usage: ${0##*/} {vm_production}"
    exit 0
}

# absolute path to this script directory (without script name)
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
APP_REPO=https://igloo.nsidc.org/REPO/nsidc_search_solr
if [ -n "$2" ]
then
  NSIDC_SOLR_VERSION=$2
  TAR_BALL=$APP_REPO/nsidc_solr_search$NSIDC_SOLR_VERSION.tar
else
  echo "Please provide an artifact version for Solr"
  exit 1
fi

DEPLOYMENT_DOMAIN=$1
if [ "$1" == "vm_production" ]
then
  DEPLOYMENT_DOMAIN="blue"
fi

VM_NETWORK="apps.int.nsidc.org"
VM_CNAME=$DEPLOYMENT_DOMAIN.$APP_NAME.$VM_NETWORK

set -x
set -e

sudo mkdir -p $APP_HOME; cd $APP_HOME; sudo chown -R vagrant .

cd $APP_HOME
wget $TAR_BALL
sudo tar -xvf $APP_HOME/nsidc_solr_search$NSIDC_SOLR_VERSION.tar
sudo chmod u+x init
sudo chown -R vagrant .
sudo chmod -R 775 .

./init start
