source 'http://rubygems.org'

gem 'rake'
gem 'rspec'
gem 'webmock', '~> 1.13.0'
gem 'turnip'
gem 'rest-client', '~> 1.6.7'
gem 'nokogiri', '~> 1.6.0'
gem 'yarjuf'
gem 'rubocop', '~> 0.12.0'
gem 'guard'
gem 'guard-rubocop'
gem 'guard-rspec'
gem 'rb-readline'
gem 'gi_cat_driver', '~> 0.3.0'
