#!/bin/bash

rake_harvest() {
   echo "Running harvest ${1}"
   rake harvest:$1
}

usage()
{
    echo "Usage: ${0##*/} {harvest|harvest-ade|environment|delete} {integration|qa|staging|production} {eol|cisl|nodc|nmi|default}"
    exit 1
}
# absolute path to this script directory (without script name)
SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPT_PATH

set -x
set -e
export RUBY_BIN=/usr/bin
export PATH=$RUBY_BIN:$PATH

sudo gem install bundler
bundle install

if [[ -z "$2" ]]
then
  env="integration"
elif [ "$2" == "integration" ] || [ "$2" == "qa" ] || [ "$2" == "staging" ] || [ "$2" == "production" ]
then
  env="$2"
else
  echo "|$2|"
  echo "Invalid environment $2 specified, please try again"
  usage
fi

if [ "$1" == "harvest" ] || [ "$1" == "harvest-nsidc" ]
then
  rake_harvest "nsidc_json[${env}]"
elif [ "$1" == "harvest-ade" ]
then
  rake_harvest "all_ade[${env}]"
elif [ "$1" == "harvest-all" ]
then
  rake_harvest "all[${env}]"
elif [ "$1" == "delete" ]
then
  rake_harvest "delete_all[${env}]"
elif [ "$1" == "environment" ]
then
  echo 'Environment setup complete'
else
  usage
fi
