#!/bin/bash

function rake_harvest(){
   bundle exec rake harvest:$1
}

usage()
{
    echo "Usage: ${0##*/} {harvest|harvest-ade|environment|delete} {integration|qa|staging|production} {eol|cisl|nodc|nmi|default}"
    exit 1
}
# absolute path to this script directory (without script name)
SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPT_PATH

set -x
set -e
export RUBY_BIN=/opt/ruby19-local/bin/
export LOCATION=/live/apps/nsidc-open-search-solr
if [ "$2" == "vm_production" ]
then
  export LOCATION=/opt/solr-search
fi
export LOCATION=/opt/solr-search
export GEM_HOME=$LOCATION/gem
export GEM_PATH=$GEM_HOME/bin
export PATH=$RUBY_BIN:$GEM_HOME:$GEM_PATH:$PATH
export PATH=/opt/jdk/bin/:$PATH   #Adding Java to the path

gem install bundler
bundle install

if [[ -z "$2" ]]
then
  env="integration"
elif [ "$2" == "integration" ] || [ "$2" == "qa" ] || [ "$2" == "staging" ] || [ "$2" == "production" ] || [ "$2" == "vm_production" ]
then
  env="$2"
else
  echo "|$2|"
  echo "Invalid environment $2 specified, please try again"
  usage
fi

if [[ -z "$3" ]]
then
  profile="CISL"
elif [ "$3" == "CISL" ] || [ "$3" == "EOL" ] || [ "$3" == "NMI" ] || [ "$3" == "NODC" ]
then
  profile="$3"
else
  echo "|$3|"
  echo "Invalid environment $3 specified, please try again"
  usage
fi

if [ "$1" == "harvest" ]
then
  rake_harvest("nsidc_json[$env]")
elif [ "$1 == "harvest-nsidc" ]
then
  rake_harvest("nsidc_json[$env]")
elif [ "$1" == "harvest-ade" ]
then
  rake_harvest("all_ade[$env]")
elif [ "$1" == "delete" ]
then
  rake_harvest("delete_all[$env]")
elif [ "$1" == "environment" ]
then
  echo "Environment setup complete"
else
   usage;
fi
