#!/bin/bash

usage()
{
    echo "Usage: ${0##*/} {harvest|environment} {integration|qa|staging|production}"
    exit 1
}
# absolute path to this script directory (without script name)
SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPT_PATH

set -x
set -e
export RUBY_BIN=/opt/ruby19-local/bin/
export LOCATION=/live/apps/nsidc-open-search-solr
export GEM_HOME=$LOCATION/gem
export GEM_PATH=$GEM_HOME/bin
export PATH=$RUBY_BIN:$GEM_HOME:$GEM_PATH:$PATH
export PATH=/opt/jdk/bin/:$PATH   #Adding Java to the path

gem install bundler
bundle install

if [[ -z "$2" ]]
then
  env="integration"
elif [ "$2" == "integration" ] || [ "$2" == "qa" ] || [ "$2" == "staging" ] || [ "$2" == "production" ]
then
  env="$2"
else
  echo "|$2|"
  echo "Invalid environment $2 specified, please try again"
  usage
fi

if [ "$1" == "harvest" ]
then
   bundle exec rake harvest:nsidc_oai_iso[$env]
elif [ "$1" == "environment" ]
then
  echo "Environment setup complete"
else
   usage;
fi


