#!/bin/bash

function stop_solr(){
    if [ -e "$PFILE" ]
    then
      PID=$(cat $PFILE)
      kill -0 $PID || true
      if [ $? -eq 0 ]
      then
        kill -15 $PID
      fi
      kill -0 $PID || tx1rue
      if [ $? -eq 0 ]
      then
        kill -9 $PID
      fi
      rm $PFILE
    else
      echo "SOLR is already stopped"
    fi
}

function start_solr(){
  if [ -e "$PFILE" ]
  then
    echo "Solr is already running/has a pidfile. Stop server or remove pidfile to start SOLR"
    exit 1
  fi
  nohup java -jar start.jar -Djetty.port=9283 --daemon > /dev/null 2>&1 &
  echo $! > $PFILE
}

usage()
{
    echo "Usage: ${0##*/} {start|stop|restart}"
    exit 0
}
# absolute path to this script directory (without script name)
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PFILE=$APP_HOME/solr.pid
cd $APP_HOME
export PATH=/opt/jdk/bin/:$PATH   #Adding Java to the path
set -x
set -e
umask 002
cd solr/example

if [ "$1" == "restart" ]
then
  stop_solr || true
  start_solr
elif [ "$1" == "stop" ]
then
  stop_solr
elif [ "$1" == "start" ]
then
  start_solr
else
  usage;
fi

