#!/bin/bash

usage()
{
    echo "Usage: ${0##*/} {start|stop|restart}"
    exit 1
}
# absolute path to this script directory (without script name)
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $APP_HOME
export PATH=/opt/jdk/bin/:$PATH   #Adding Java to the path

set -x
set -e

echo "RESTART"
cd solr/example

if [ "$1" = "restart" ]
then
  java -jar start.jar -stop
  java -jar start.jar -Djetty.port=9283
elif [ "$1" == "stop" ]
then
  java -jar start.jar --stop
elif [ "$1" == "start" ]
then
  java -jar start.jar -Djetty.port=9283
else
  usage;
fi


