# Data format mappings from what appears in the metadata to facet bin.
module NsidcFormatMapping
  MAPPING = {
    '.*ArcGIS.*' => 'ArcGIS Native',
    '.*ESRI Grid.*' => 'ArcGIS Native',
    '.*ESRI Interchange.*' => 'ArcGIS Native',
    '.*ESRI Shapefiles.*' => 'ArcGIS Native',
    '.*ASCII Text \(\.txt\).*' => 'ASCII Text',
    '.*Binary.*' => 'Binary',
    '.*IMG.*' => 'Binary',
    '.*JPS.*' => 'Binary',
    '.*LMRF.*' => 'Binary',
    '.*Comma-Separated Values \(\.csv\).*' => 'CSV',
    '.*Microsoft Access \(\.mdb\).*' => 'Database',
    '.*Microsoft PowerPoint.*' => 'Documents',
    '.*Microsoft Word.*' => 'Documents',
    '.*Paper.*' => 'Documents',
    '.*PDF.*' => 'Documents',
    '.*Microsoft Excel.*' => 'Microsoft Excel',
    '.*Geographic Tagged Image File Format \(GeoTIFF\) \(\.geotiff\).*' => 'GeoTIFF',
    '.*HDF.*' => 'HDF/HDF-EOS',
    '.*HDF-EOS.*' => 'HDF/HDF-EOS',
    '.*GIF.*' => 'Image Files',
    '.*JPEG.*' => 'Image Files',
    '.*Photoshop.*' => 'Image Files',
    '.*PNG.*' => 'Image Files',
    '.*(?i)(?<!geo)(?-i)TIFF.*' => 'Image Files',
    '.*GML.*' => 'KML/GML',
    '.*Keyhole Markup Language \(\.kml\).*' => 'KML/GML',
    '.*ENVI Vector File \(\.evf\).*' => 'Vector Files',
    '.*Generic Mapping Tools \(\.gmt\).*' => 'Vector Files',
    '.*Audio Video Interleave \(\.avi\).*' => 'Video Files',
    '.*MPEG.*' => 'Video Files',
    '.*DXF.*' => 'exclude',
    '.*IRL.*' => 'exclude',
    '.*SEGY.*' => 'exclude',
    '.*TWF.*' => 'exclude',
    '.*WFS.*' => 'exclude',
    '.*WMS.*' => 'exclude',
    '.*XML.*' => 'exclude'
  }
end
