#!/bin/sh

# run the specs locally to prevent pushes that would break the Jenkins builds

case "${1}" in
    --about )
        echo "Run the RSpec tests."
        ;;
    * )
        rspec
        ;;
esac
