name: Search Solr Tools Unit Tests
run-name: ${{ github.actor }} is running unit tests
on:
  workflow_dispatch:
  pull_request:
jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server."
      - run: echo "The branch is ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: run tests
        run: |
          bundle exec rake spec:unit
      - run: echo "This job's status i ${{ job.status }}."